### ISSUE TITLE
Running with Python 2.7.13 produces error?

### ISSUE THREAD

**Issue by cmdcolin** [danvk/RangeHTTPServer#16]
Running with python -m RangeHTTPServer

```
$ python -m RangeHTTPServer
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/RangeHTTPServer/__main__.py", line 24, in <module>
    SimpleHTTPServer.test(HandlerClass=RangeRequestHandler)
AttributeError: 'module' object has no attribute 'test'
```

Tried reinstalling just in case but seems to still have the error

```
pip install --upgrade --force-reinstall RangeHTTPServer
Collecting RangeHTTPServer
  Using cached rangehttpserver-1.2.0-py2.py3-none-any.whl
Installing collected packages: RangeHTTPServer
  Found existing installation: rangehttpserver 1.2.0
    Uninstalling rangehttpserver-1.2.0:
      Successfully uninstalled rangehttpserver-1.2.0
Successfully installed RangeHTTPServer-1.2.0
```

Python3 does work though (installed via pip3 install RangeHTTPServer)

**Comment by danvk** [comment]
I just installed `RangeHTTPServer` with python 2.7.13 and do not get that error.

```
$ sudo pip2 install RangeHTTPServer
Collecting RangeHTTPServer
  Downloading rangehttpserver-1.2.0-py2.py3-none-any.whl
Installing collected packages: RangeHTTPServer
Successfully installed RangeHTTPServer-1.2.0

$ python --version
Python 2.7.13

$ python -m RangeHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

**Comment by cmdcolin** [comment]
Maybe there is something weird with my system. I must say I am terrible at python but I tried changing this file /usr/local/lib/python2.7/site-packages/RangeHTTPServer/__init__.py to say

```
import os
import re

try:
    # Python3
    print 'I think I am python 3'
    from http.server import SimpleHTTPRequestHandler

except ImportError:
    print 'I think I am python 2'
    # Python 2
    from SimpleHTTPServer import SimpleHTTPRequestHandler
```

Then I end up with this?

```
$ python --version
Python 2.7.13
$ python -m RangeHTTPServer                                             
I think I am python 3
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/RangeHTTPServer/__main__.py", line 24, in <module>
    SimpleHTTPServer.test(HandlerClass=RangeRequestHandler)
AttributeError: 'module' object has no attribute 'test'
```


Not sure if it is a crazy homebrew thing or what now!

**Comment by cmdcolin** [comment]
Actually I wasn't reading the code very closely. It looks like it tries the python3 approach in all cases and falls back to python2, but it never does seem to get to the point of falling back to python2? ...

**Comment by cmdcolin** [comment]
Just saw this error again with Bash on Windows using linuxbrew python 2.7.13 but it worked with the default python 2.7.6  that Bash on Windows ships with

Then I tried it on lubuntu 16 with python 2.7.12 by default, and then with linuxbrew which is 2.7.13 and both worked actually so that is sort of weird...maybe 2.7.12 and 2.7.13 are close enough so as to not cause conflict?

This original bug was based on what I saw on macos sierra (using homebrew python 2.7.13) didn't try the default system version of python there


I'm still kind of confused but if I am looking at the error a little more closely I can see it is referencing both /usr/local/Celler/python/... and /usr/local/lib/python2.7/... not sure if that is normal

**Comment by danvk** [comment]
I'm going to close this out since it's so old. If you or anyone else run into a similar issue, please reopen.
